// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kursovaya;

#nullable disable

namespace kursovaya.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241212094848_initialmigr")]
    partial class initialmigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kursovaya.Models.Table", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("b1")
                        .HasColumnType("real");

                    b.Property<float>("i")
                        .HasColumnType("real");

                    b.Property<float>("mddn")
                        .HasColumnType("real");

                    b.Property<float>("rmosh")
                        .HasColumnType("real");

                    b.Property<float>("rnr")
                        .HasColumnType("real");

                    b.Property<float>("t")
                        .HasColumnType("real");

                    b.Property<float>("z2")
                        .HasColumnType("real");

                    b.Property<float>("zp")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("kursovaya.Models.Vivod", b =>
                {
                    b.Property<int>("ID1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID1"));

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID1");

                    b.HasIndex("TableId")
                        .IsUnique();

                    b.ToTable("Vivods");
                });

            modelBuilder.Entity("kursovaya.Models.Vivod", b =>
                {
                    b.HasOne("kursovaya.Models.Table", "Table")
                        .WithOne("Vivod")
                        .HasForeignKey("kursovaya.Models.Vivod", "TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("kursovaya.Models.Table", b =>
                {
                    b.Navigation("Vivod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
